Add Geometry fixes for reconciled catchments and length map calculations
dblodgett-usgs/hyRefactor pull request #17
Opened 2021-09-15 19:24 UTC by mikejohnson51

Hi @dblodgett-usgs,

This PR address #16. Functions are exported directly, and embedded in `reconcile_catchment_divides` with the flag "fix_catchments". 

The package builds and loads correctly.

Test are written in `test_geometries.R` based on a minimal dataset created in `inst/extdata/gage_01013500_data.R` and stored in `inst/extdata`

Structural package changes includes moving `rgeos` from Suggests to Imports, and adding `rmapshaper` to Imports.

Mini Example of new usage: 

```{r}
divides  <- reconcile_catchment_divides(catchment = catchments,
                                             fline_ref  = fline_ref,
                                             fline_rec = fline_rec,
                                              fdr         = fdr,
                                             fac         = fac,
                                             para       = 1, 
                                             cache    = NULL,
                                             fix_catchments = TRUE) 
```

This PR also adds functionality for producing length mappings for member_COMIDs via a function called `add_lengthmap`.

2021-09-19 16:11 UTC, dblodgett-usgs requested changes

2021-09-19 16:11 UTC, dblodgett-usgs commented on R/catchment_geometry.R
> +catchment_geometry_doctor = function(catchments,
Can we change this function to be more in line with others in the package? e.g. `clean_geometry` or some such?

2021-09-19 16:11 UTC, dblodgett-usgs commented on R/catchment_geometry.R
> +#' network but adds a new notion. Following each COMID is '.' which is proceeded
It doesn't add a new "notion" -- it adds a new column. 

It seems like this would be better as a new table or a list column in the current table? I used the .1, .2, .3 notation to indicate that a flowline was broken into pieces already, but the identifiers are still identifiers. I'm not comfortable using a different (and potentially similar looking) notation for fractional membership. 

Happy to have the functionality, but can you suggest a different way to record it that will be more clear?

2021-09-19 16:11 UTC, dblodgett-usgs commented on R/reconcile.R
>      attr(replace_cat, "sf_column") <- attr(out, "sf_column")
Could call one of the geometry rename functions here?

2021-09-20 20:49 UTC, mikejohnson51 commented on R/catchment_geometry.R
> +}
Sure, will change

2021-09-20 22:18 UTC, mikejohnson51 commented on R/catchment_geometry.R
> +}
I changed the name but left it as exported since it is used in aggregation workflows routinely.

2021-09-20 22:18 UTC, mikejohnson51 commented on R/catchment_geometry.R
> +spCatMerge = function(poly, ID){
finnnnnneeeeeeeee :P

2021-09-20 22:19 UTC, mikejohnson51 commented on R/catchment_geometry.R
> +catchment_geometry_doctor = function(catchments,
clearly I can't name functions ha!

2021-09-20 22:21 UTC, mikejohnson51 commented on R/catchment_geometry.R
> +#' network but adds a new notion. Following each COMID is '.' which is proceeded
Hmmm, so for my use case I want to weight NHD/RouteLink variables by associated COMID. This is a really clear way to do so but the column is only added when the function is called and the name is user defined. So hopefully it is only added when a person explicitly wants it and knows what to do with it?

2021-09-22 01:13 UTC, merged